title: CodeVibe Design System
description: Modern minimalistic coding-inspired design system concept for VERSA 1.0
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false
