title: DotAISlash
description: Home of VERSA – Vendor-neutral Extensible Repo Spec for Agents – and the CodeVibe design system.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false
